### ISSUE TITLE
Votes rewards

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1251]
## Is your feature request related to a problem? Please describe.

So while implementing/designing collection of votes for rewards, I realized one thing, which is pretty important and might make us rethink the approach... Another possibility is that I still did not get 100% Justin's idea :).

The problem is db size. According [this measurement](https://github.com/Taraxa-project/taraxa-node/issues/1053) that Matus did few weeks ago (node running for 2 or 3 weeks), dag_blocks = 12GB, TXS = 6GB, CERT_VOTES = 6GB(Miho refactored this so these 3 objects types are  now in period_data now but it was not optimized in terms of size) Our idea is to put whole votes into the dag blocks, so in case we would like to reward voting in all steps(there is 5 steps if I am not mistaken), thats 6GB * 5 = 30 GB. Even if we would reward only cert votes, which are already saved in db in period_data column and we put it also into dag blocks, that would mean duplicate votes in db: 6 GB * 2 >= 12 GB. I put here > because if we want to be fair we should probably save & reward all valid votes and not only 2t+1... 

### Original optimized solution:
Originally I though we can put only hashes of votes from previous round into the dag blocks. It is probably not possible because:

-  we cant wait forever to receive all votes so once we receive 2t + 1 votes lets say for period 1, we save it inside period_data and move on, period 2 consensus starts etc... So we have 2t + 1 saved in db for period 1 but we might receive dag block that contains vote hash (from period 1), which we dont have in our db. The other node could send us missing full votes before dag block, but we would have to resave it into the period 1 data, which was already saved in db otherwise we would serve incomplete syncing data (without those missing votes). And even if we do it if someone request syncing data for period 1 before we finish period 2 (potentially add some votes into db for period 1), we will serve incomplete data. + I am not sure if we can resave already saved data for previous period, probably not...

### New solution:

Challenges that we face:

- In my understanding we simply have to add full votes into the dag blocks (no other way around - hashes wont work...)
- Currently votes consume too much memory 
- because those votes probably have to be duplicate in db - it is simply not maintainable as it would consume 2x or even more memory
- I think we have to implement weighted votes instead of what we have now(1 STAKE = 1 VOTE). 

So it seems that we need weighted votes that would significantly save db size for votes -> we could even live with the fact that votes are duplicated in db.

**Comment by gaoqi8649** [comment]
In my understanding, votes will be included in DAG blocks as a kind of transaction. Since the current PBFT committee size setup to 1000 (this is in config file we can change it), the maximum vote transactions are 1000 TPS. I agree if we could reduce votes size that will improve system performance and saving resources. But 1000 TPS vote transactions should not be a block limitation in our system and we cannot handle it.

I agree with Miho, we should not duplicate votes in DB. How about we do like this:
Create a new column “votes” in DB for saving all full votes. 
All other columns that using votes, like “soft votes”, “cert votes”, “next votes” and the new vote transations in DAG block will change to use hash only
When node receive a DAG block include the votes that node doesn’t have, wait for votes gossiping or send request asking for missing votes

For weighted votes, we had discussed in previous meeting. The idea votes in weighted stakes voting independently, when we have a large number of nodes in network, VRF sortition will make number of votes are close to committee size. Vote has “weighed index” to determine DPOS state availability and VRF sortition. For each weighted index will generate its own VRF sortition proof and output values. So if put all weighted indexes VRF sortition structure into one vote. Then the one weighted vote size is almost equal to sum of all current votes. So there is no size saving for weighted votes.

**Comment by JakubFornadel** [comment]
@gaoqi8649 

For the first part:
- Almost nothing is a blocker, you can still run node in a server with bigger disc, more memory and more cpu cores, but that is not very good approach. Users will have to pay a lot of money per month for servers... That is why we have to make everything as effective as possible. 

Second part:
- There is 1 important thing that you have to think about. As I described above: when you receive 2t + 1 votes, you save it, finalize pbft block and move on to the next period. Then you receive new dag block with a vote from previous pbft period that you dont have so you would have to add it into the period_data column that you already saved before. So this solution would require removing votes from period_data column + it still would not work in edge case when someone is 1 pbft period behind and triggers syncing from you

Third part:
-  I dont understand, need a call to discuss it
