### ISSUE TITLE
Dag block txs ordering

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1481]
## Task Description

Ledger is not correctly ordering transactions when creating dag blocks. We keep unexecuted txs inside unordered map and when creating dag block, 250 txs are retrieved from unordered map by iterating over the map from the beginning - this means those 250 txs are basically random. Then they are ordered by sender & nonce. Problem is that for example if there is 10k txs in tx pool already and sender A sends 2 txs: TX1 with nonce 1 and fee 10 and TX2 with nonce 2 and fee 5, it is possible that due to randomness TX2 will be saved at the beggining of the transaction pool and TX1 at the end, so TX2 will be executed first and fails due to invalid nonce.... This should never happen

Solution
Create much more sophisticated tx pool, which would serve 250 ordered txs based on fee & sender & nonce ?
See eth ordering algo here:
https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/core/types/transaction.go#L372

## Epic Parent

[Feature: Transaction ordering & delegation process](https://github.com/Taraxa-project/taraxa-node/issues/1480).

**Comment by gaoqi8649** [comment]
I am not familiar with transactions part of code. I have a few questions, @JakubFornadel @mfrankovi @MatusKysel please take a look on below questions:

1. Above mentioned transactions ordered by sender & nonce. How is possible TX2 saved before TX1? TX1 should have a small nonce than TX2, I think transactions pool use “set” or “map” for saving transitions by nonce ( in address) order

2. Why tx with higher fee should be prioritized as first? I think should execute transactions as nonce order for address. In the above example, The total fee should be 15, If sender don’t have enough fee, that will either failed at TX1 or TX2. I don’t understand why higher fee transactions should have high priority.
For example:
Node1 balance 5
Tx1 node1 deposite 100, fee 5, nonce 1
Tx2 node1 withdraw 50, fee 10, nonce 2
We have to execute the 2 txs in order by nonce, and not by fee. Otherwise will fail execute at both trxs

**Comment by JakubFornadel** [comment]
@gaoqi8649 
1. You dont need to be familiar with this part of codebase, just check the code what structure does tx pool use ?  I see `ThreadSafeMap<trx_hash_t, std::shared_ptr<Transaction>> transactions_pool_;`, how is can be this ordered by nonce ?

2. You are right that that is a typo, nonce cannot be skipped so tx with nonce 2 cant be executed before tx with nonce 1, I will fix that in description
