### ISSUE TITLE
Limit pbft & dag blocks size

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1496]
## Task Description

Limit the size of PBFT blocks to prevent massive blocks after network stalling / partitioning by:

- max total size
- max number of dag blocks in pbft block
- max total number of txs in pbft block(related to number of dag blocks)
- max used gas for included txs

Note: It is possible that we create such huge pbft block, which will fail inside evm due to "gas limit". If there is gas limit on blocks, others limits (txs number/size) might not be needed anymore ?

**Comment by MatusKysel** [comment]
I still think about this crazy idea, that we would not calculate gas estimate before executing transaction, but simply use gas limit. In case you will have not enough trx will fail and when you set limit to really high number then we would move unused gas to reward pool or something like that. This way it would be much easier to handle transactions

**Comment by kstdl** [comment]
My current idea is to estimate transaction gas limit during dag block creation. During it we will know dag level and we can get proposal period from the mapping. We will launch estimation(transaction execution) with proposal period as block number, but not finalized block number. Because of this we will be consistent in calculations and could verify it. But we will have at least one not big problem that is incorrect estimations of some calls. It could happen because proposal period may lag behind the finalized period. So could be a situation when contract was already created at block 100, but most recent call of that contract estimates on 80 proposal period and we try to call non-existing contract in that state. Another one thing is that values could change with the state and block. Because it could affect only that our limit mechanism and its estimation, but not the execution and other stuff I guess it is not a problem and it should not lead to big underestimates of transactions. 

Other option there is to calculate limit just by gas_limit from the transaction as @MatusKysel offers. But the issue with it is that you can set any gaslimit to transaction. We can't check that you used estimate method, but not just set it manually. And with default logic you will spend only used part, but not the estimated. So you will receive some odd money after execution. Also if transaction fails it will use all gaslimit. All allocated funds will be spent on the transaction. This leaves room for malicious behavior, including bandwidth throttling

**Comment by MatusKysel** [comment]
I see your point @kstdl mine idea would be only working in case we do not need to be 100% same as ethereum, that we would not return any gas that won't be used. Anyway I do not see room for malicious player, as any attempts will punished by removing fees from his balance

**Comment by kstdl** [comment]
I don't like idea to not return unused gas. It is work with money, so we need to be careful with decisions like this. Seems like not very clear situation if we are using Ethereum API, but have that kind of differences in implementation. Users will have a question why you don't returning it if you not need it all.  Also it is kind of complication because user will need to be more careful with fees just to not waste more than transaction is actually needed
