### ISSUE TITLE
Votes syncing

### ISSUE THREAD

**Issue by mfrankovi** [Taraxa-project/taraxa-node#1503]
Nodes keep verified votes from the current round in memory. Once a node is restarted it loses these votes and these votes are not synced. If a lot of nodes that are part of the consensus restart at the same time and especially if they are in the same round but different steps this can cause the network to get stalled. There is a need to sync votes for all the steps in the current round from other nodes on restart. 

Create similar syncing to dag blocks syncing

**Comment by gaoqi8649** [comment]
Nodes save their own votes in DB. And will rebroadcast the votes after restart. If a lot of nodes restart at the same time, all of the nodes will rebroadcast their own votes after restart.
https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp#L32

The issue is when node just restart, they may have no peers connection. Need add delay for nodes connect to each other
