### ISSUE TITLE
Include previous pbft block votes hashes in proposed pbft block

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1604]
## Task Description

To reward voting, we need to be able to somehow validate these votes from the previous round, but at the same time keep the pbft block as small as possible.

Solution:

- pbft block proposer includes votes hashes that he saw in the previous round  
- when he broadcast the block, he has to make sure the receiver has all the votes (full objects) from this list of votes hashes he include d in the proposed pbft block - similar mechanism to dag blocks included in pbft block
- each proposer must include at least 2/3+1 votes, but we want validators to include as many votes as possible -> pbft block proposer should be rewarded more if includes more than 2/3+1 votes

Previously we tried an approach, when these votes were included in dag blocks, but it was VERY complicated and it significantly affected the performance due to extensive db writes that had to be processed.

## Epic Parent

[Feature: Implement rewards distribution](https://github.com/Taraxa-project/taraxa-node/issues/1413).

**Comment by gaoqi8649** [comment]
Do we only reward the voters that include in PBFT blocks?
Like node may include 2/3 + 1 voters in PBFT block, still have 1/3 voters not include in PBFT block. Do the 1/3 voters will not get reward even they do voting?

**Comment by JakubFornadel** [comment]
> Do we only reward the voters that include in PBFT blocks? Like node may include 2/3 + 1 voters in PBFT block, still have 1/3 voters not include in PBFT block. Do the 1/3 voters will not get reward even they do voting?

correct

**Comment by gaoqi8649** [comment]
I have concerns. Since committee size is 1000, max 2t+1 is 667. Nodes may have cert votes different from each others.

1. If include votes hash in proposed blocks, process will like:
(1). Node1 send proposed block to node2
(2). Node2 check proposed block, and find missing cert votes. Node2 send missing cert votes hash request to node1 
(3). Node1 send the node2’s missing cert votes to node2
(4). When node2 receive all missing cert votes, node2 be able to verify the node1’s proposed block
That extend the proposed block verification time. And PBFT require that has to be done within 2 lambda time. If no 2t+1 nodes finish that within 2 lambda time, the PBFT round will not be able to produce blocks. And that will effect yield rate.

2. If include votes full objects in proposed blocks, that will have at most 667 votes objects. That makes PBFT blocks object too big. That will effect deliver time to peers

**Comment by gaoqi8649** [comment]
I have some ideas for the task, that may have some help
1. The cert votes syncing cannot like DAG blocks. Because DAG blocks has parents blocks info, and votes are more independent from each other
2. Don’t just saving 2t+1 cert votes, saving as much as we can.
3. Separate cert votes from period blocks column in DB, and create a new column for saving cert votes. Then we will be able to saving cert votes even after finalizing PBFT blocks.
4. Then we will have at least a round time(from current period cert voting state to next period cert voting state ) to receive all cert votes for the previous finalized PBFT block
5. When cert voting blocks, if still have missing cert votes, send syncing request by vote hash since we have all cert votes hash in PBFT proposal blocks.

**Comment by MatusKysel** [comment]
@gaoqi8649 since this task is again your's, just few of mine comments:

1. I do not think we need vote syncing, as we are gossiping then around
2. agree
3. no 100% this is right, what I would do, is that I would create some intermediate column for current block N and when we receive block N + 1 then remove them and save them with block N
4. I guess so
5. Actually I think easier to implement, would be to send pbft block with all votes that you are missing as we are marking them, then you do not need to create complicated syncing. If gossiping works right, you should already have most of them

complicated syncing could be done later, when we could say, that we are sending way too many votes with pbft block
